version: '3.8'

services:
  cashflowtracker-api:
    build:
      context: .
      dockerfile: src/CashFlowTracker.API/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    restart: always

  transaction-worker:
    build:
      context: .
      dockerfile: src/CashFlowTracker.TransactionWorker/Dockerfile
    environment:
      - "MONGO_URI=mongodb://mongodb:27017"
      - "REDIS_URI=redis://redis:6379"
      - "RABBITMQ_URI=amqp://rabbitmq"

  consolidation-worker:
    build:
      context: .
      dockerfile: src/CashFlowTracker.ConsolidationWorker/Dockerfile
    environment:
      - "MONGO_URI=mongodb://mongodb:27017"
      - "REDIS_URI=redis://redis:6379"
      - "RABBITMQ_URI=amqp://rabbitmq"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data:
