version: '3.8'

services:
  cashflowtracker-api:
    build:
      context: .
      dockerfile: src/CashFlowTracker.API/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver
      - redis
      - rabbitmq
    restart: always

  transaction-worker:
    build:
      context: .
      dockerfile: src/CashFlowTracker.TransactionWorker/Dockerfile
    environment:
      - "SQLSERVER_URI=Server=sqlserver,1433;Database=CashFlowTrackerDb;User Id=sa;Password=OurStrong!Passw0rd;"
      - "REDIS_URI=redis://redis:6379"
      - "RABBITMQ_URI=amqp://rabbitmq"

  consolidation-worker:
    build:
      context: .
      dockerfile: src/CashFlowTracker.ConsolidationWorker/Dockerfile
    environment:
      - "SQLSERVER_URI=Server=sqlserver,1433;Database=CashFlowTrackerDb;User Id=sa;Password=OurStrong!Passw0rd;"
      - "REDIS_URI=redis://redis:6379"
      - "RABBITMQ_URI=amqp://rabbitmq"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "OurStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./devops:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
